#!/bin/bash

set -euo pipefail

echo "========================================"
echo "VotingWithSBT 재배포 시작"
echo "========================================"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(realpath "${SCRIPT_DIR}/..")"
PROJECT_ROOT="$(realpath "${CONTRACTS_DIR}/..")"
ARTIFACT_PATH="${CONTRACTS_DIR}/artifacts/sbt_deployment.json"
ESCROW_ARTIFACT_PATH="${CONTRACTS_DIR}/artifacts/escrow_deployment.json"
FRONTEND_DIR="${CONTRACTS_DIR}/../frontend"
FRONTEND_ENV="${FRONTEND_DIR}/.env.local"

cd "$CONTRACTS_DIR"

if [ -f "deploy.env" ]; then
  echo "📄 deploy.env 로드 중..."
  set -a
  source deploy.env
  set +a
  echo "✅ 환경 변수 로드 완료"
  echo ""
fi

echo "🔗 RPC 연결 확인 중..."
RPC_URL="${NODE_URL:-${RPC_URL:-http://localhost:9545}}"
if ! curl -s -X POST "$RPC_URL" \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' > /dev/null 2>&1; then
  echo "❌ RPC 서버에 연결할 수 없습니다: $RPC_URL"
  exit 1
fi
echo "✅ RPC 연결 성공"
echo ""

if [ -f "$ARTIFACT_PATH" ]; then
  BACKUP_FILE="${ARTIFACT_PATH}.backup.$(date +%s)"
  echo "📦 기존 VotingWithSBT 배포 정보 백업: $BACKUP_FILE"
  cp "$ARTIFACT_PATH" "$BACKUP_FILE"
  echo ""
fi

# Generate NFT metadata if configured
if [ -n "${NFT_NAME:-}" ] && [ -n "${MASCOT_CID:-}" ] && [ -n "${PINATA_API_KEY:-}" ] && [ -n "${PINATA_SECRET_KEY:-}" ]; then
    echo "🎨 NFT 메타데이터 생성 중..."
    
    # Run metadata generator and capture output
    GENERATOR_OUTPUT=$(node "${PROJECT_ROOT}/scripts/generate_nft_metadata.js" \
        --image "${MASCOT_CID}" \
        --ballot "${BALLOT_ID:-citizen-2025}" \
        --name "${NFT_NAME}" 2>&1)
    
    EXIT_CODE=$?
    
    if [ $EXIT_CODE -eq 0 ]; then
        # Read CID from the file generated by the script
        if [ -f ".last_metadata_cid" ]; then
            METADATA_CID=$(cat ".last_metadata_cid")
            rm ".last_metadata_cid" # Clean up
        else
            # Fallback to parsing output if file doesn't exist (shouldn't happen)
            METADATA_CID=$(echo "$GENERATOR_OUTPUT" | grep "^  CID:" | awk '{print $2}' | tail -n 1)
        fi

        if [ -n "${METADATA_CID}" ]; then
            echo "✅ 메타데이터 생성 완료: ${METADATA_CID}"
            echo "⚠️  MASCOT_CID를 메타데이터 CID로 덮어씁니다"
            export MASCOT_CID="${METADATA_CID}"
        else
            echo "❌ 메타데이터 CID를 찾을 수 없습니다"
            echo "출력 내용:"
            echo "$GENERATOR_OUTPUT"
            echo "⚠️  원본 MASCOT_CID(이미지)를 사용합니다"
        fi
    else
        echo "❌ 메타데이터 생성 스크립트 오류 (Exit Code: $EXIT_CODE)"
        echo "출력 내용:"
        echo "$GENERATOR_OUTPUT"
        echo "⚠️  원본 MASCOT_CID(이미지)를 사용합니다"
    fi
elif [ -n "${NFT_NAME:-}" ] && [ -n "${MASCOT_CID:-}" ]; then
    echo "⚠️  NFT_NAME이 설정되었지만 Pinata 키가 없습니다"
    echo "📄 MASCOT_CID를 그대로 사용합니다 (메타데이터 생성 없음)"
elif [ -n "${MASCOT_CID:-}" ]; then
    echo "📄 deploy.env의 MASCOT_CID 사용"
fi

echo "🚀 VotingWithSBT 단일 재배포 실행"
node "${SCRIPT_DIR}/redeploy_voting_contract.js"
echo ""

if [ ! -f "$ARTIFACT_PATH" ]; then
  echo "❌ 재배포 이후 artifact 파일을 찾을 수 없습니다"
  exit 1
fi

VOTING_ADDRESS=$(node -pe "JSON.parse(require('fs').readFileSync('$ARTIFACT_PATH','utf8')).contracts.VotingWithSBT.address")
SBT_ADDRESS=$(node -pe "JSON.parse(require('fs').readFileSync('$ARTIFACT_PATH','utf8')).contracts.CitizenSBT.address")
REWARD_ADDRESS=$(node -pe "JSON.parse(require('fs').readFileSync('$ARTIFACT_PATH','utf8')).contracts.VotingRewardNFT.address")
VERIFIER_ADDRESS=$(node -pe "try { JSON.parse(require('fs').readFileSync('$ARTIFACT_PATH','utf8')).contracts.CitizenSBT.verifier } catch(e) { '' }")
ESCROW_ADDRESS=$(node -pe "try { JSON.parse(require('fs').readFileSync('$ESCROW_ARTIFACT_PATH','utf8')).address } catch(e) { '' }")

echo "📍 신규 VotingWithSBT 주소: $VOTING_ADDRESS"
echo ""

if [ -f "$FRONTEND_ENV" ]; then
  echo "🔄 프론트엔드 .env.local 업데이트 중..."
  cp "$FRONTEND_ENV" "${FRONTEND_ENV}.backup.$(date +%s)"
  sed -i "s|^REACT_APP_VOTING_CONTRACT_ADDRESS=.*|REACT_APP_VOTING_CONTRACT_ADDRESS=$VOTING_ADDRESS|" "$FRONTEND_ENV"
  sed -i "s|^REACT_APP_CITIZEN_SBT_ADDRESS=.*|REACT_APP_CITIZEN_SBT_ADDRESS=$SBT_ADDRESS|" "$FRONTEND_ENV"
  sed -i "s|^REACT_APP_REWARD_NFT_ADDRESS=.*|REACT_APP_REWARD_NFT_ADDRESS=$REWARD_ADDRESS|" "$FRONTEND_ENV"
  if grep -q "^REACT_APP_SIMPLE_ESCROW_ADDRESS=" "$FRONTEND_ENV"; then
    sed -i "s|^REACT_APP_SIMPLE_ESCROW_ADDRESS=.*|REACT_APP_SIMPLE_ESCROW_ADDRESS=${ESCROW_ADDRESS:-<escrow-address>}|" "$FRONTEND_ENV"
  else
    echo "REACT_APP_SIMPLE_ESCROW_ADDRESS=${ESCROW_ADDRESS:-<escrow-address>}" >> "$FRONTEND_ENV"
  fi
  echo "✅ 프론트엔드 환경 변수 업데이트 완료"
  echo "  파일: $FRONTEND_ENV"
  echo ""
else
  echo "⚠️  프론트엔드 .env.local 파일을 찾을 수 없습니다. 수동 업데이트 필요"
fi

# 프론트엔드 config.json 업데이트
CONFIG_FILE="${FRONTEND_DIR}/public/config.json"
mkdir -p "$(dirname "$CONFIG_FILE")"
# 기존 config에서 SIMPLE_ESCROW_ADDRESS가 비어 있고, artifact에도 없을 때는 기존 값을 유지
if [ -z "$ESCROW_ADDRESS" ] && [ -f "$CONFIG_FILE" ]; then
  ESCROW_ADDRESS=$(node -pe "try { JSON.parse(require('fs').readFileSync('$CONFIG_FILE','utf8')).SIMPLE_ESCROW_ADDRESS || '' } catch(e) { '' }")
fi
# 그래도 없으면 .env.local 값 사용
if [ -z "$ESCROW_ADDRESS" ] && [ -f "$FRONTEND_ENV" ]; then
  ESCROW_ADDRESS=$(grep "^REACT_APP_SIMPLE_ESCROW_ADDRESS=" "$FRONTEND_ENV" | head -n1 | cut -d= -f2-)
fi

echo "🔄 프론트엔드 config.json 업데이트 중..."
cat > "$CONFIG_FILE" <<EOF
{
  "CITIZEN_SBT_ADDRESS": "$SBT_ADDRESS",
  "VOTING_CONTRACT_ADDRESS": "$VOTING_ADDRESS",
  "REWARD_NFT_ADDRESS": "$REWARD_ADDRESS",
  "SIMPLE_ESCROW_ADDRESS": "$ESCROW_ADDRESS",
  "VERIFIER_ADDRESS": "$VERIFIER_ADDRESS",
  "RPC_URL": "http://localhost:9545",
  "CHAIN_ID": "0x539",
  "CHAIN_NAME": "Quorum Local",
  "EXPECTED_VOTERS": 1000
}
EOF
echo "✅ config.json 업데이트 완료"

VOTING_ABI_SOURCE="${CONTRACTS_DIR}/artifacts/VotingWithSBT.abi.json"
VOTING_ABI_TARGET="${FRONTEND_DIR}/src/abi/VotingWithSBT.abi.json"
if [ -f "$VOTING_ABI_SOURCE" ]; then
  mkdir -p "$(dirname "$VOTING_ABI_TARGET")"
  cp "$VOTING_ABI_SOURCE" "$VOTING_ABI_TARGET"
  echo "📁 VotingWithSBT ABI를 프론트엔드에 복사했습니다"
  echo "  -> $VOTING_ABI_TARGET"
  echo ""
else
  echo "⚠️ VotingWithSBT ABI 파일을 찾을 수 없어 복사를 건너뜁니다"
fi

echo "========================================"
echo "✅ VotingWithSBT 재배포 완료"
echo "========================================"
echo "다음 단계를 수행하세요:"
echo "다음 단계를 수행하세요:"
echo "  1. 브라우저를 새로고침(F5)하여 새 주소를 반영하세요"
echo "  2. 필요한 경우 백엔드 환경 변수(CITIZEN_SBT_CONTRACT_ADDRESS 등)를 확인하세요"
echo "========================================"
